### ISSUE TITLE
有一个拼写错误，TrustOceanSSLAdmin.php 页面

### ISSUE THREAD

**Issue by Vicshs** [londry/TRUSTOCEAN-WHMCS#13]
47行
`            $table->timestamp('checkcert_cliecked')->nullable();
`

**Comment by Vicshs** [comment]
正确书写应是checkcert_clicked。

不然会导致用户查询签发状态时500.

**Comment by londry** [comment]
此问题已经确认，预计今晚推送更新。

**Comment by londry** [comment]
此问题已经推送更新修复 dev 分支中
